### ISSUE TITLE
Access Denied trace error when running snippet

### ISSUE THREAD

**Issue by giorgio79** [OfficeDev/office-js-snippet-explorer#13]
Error (I am using a local network share folder)
>{"name":"OfficeExtension.Error","code":"AccessDenied","message":"AccessDenied","traceMessages":[],"debugInfo":{"errorLocation":"Body.getHtml"},"stack":"AccessDenied: AccessDenied\n   at Anonymous function (https://eus-appsforoffice.edog.officeapps.live.com/afo/lib/1.1/hosted/word-win32-16.00.js:19:150094)\n   at yi (https://eus-appsforoffice.edog.officeapps.live.com/afo/lib/1.1/hosted/word-win32-16.00.js:19:163912)\n   at st (https://eus-appsforoffice.edog.officeapps.live.com/afo/lib/1.1/hosted/word-win32-16.00.js:19:163999)\n   at d (https://eus-appsforoffice.edog.officeapps.live.com/afo/lib/1.1/hosted/word-win32-16.00.js:19:163819)\n   at c (https://eus-appsforoffice.edog.officeapps.live.com/afo/lib/1.1/hosted/word-win32-16.00.js:19:162405)"}
Debug info: {"errorLocation":"Body.getHtml"}

**Comment by MIchaelMainer** [comment]
@giorgio79 Can you confirm whether this error occurs on all snippets or just this one? FYI - I've updated the sample to point at the correct CDN.

**Comment by giorgio79** [comment]
@MIchaelMainer Thx for coming back. Yes. On all. Here is a new trace with the new location.

> Error: {"name":"OfficeExtension.Error","code":"AccessDenied","message":"AccessDenied","traceMessages":[],"debugInfo":{"errorLocation":"Body.getOoxml"},"stack":"AccessDenied: AccessDenied\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.00.js:19:150094)\n   at yi (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.00.js:19:163912)\n   at st (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.00.js:19:163999)\n   at d (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.00.js:19:163819)\n   at c (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.00.js:19:162405)"}
Debug info: {"errorLocation":"Body.getOoxml"}
No content control found.

**Comment by giorgio79** [comment]
Possibly related issue that I encountered when trying to get the Word demo going https://github.com/OfficeDev/office-js-docs/issues/23

**Comment by MIchaelMainer** [comment]
@giorgio79 I haven't tried using a _local_ network share before. There may be some issue with that (and I don't know what settings to change to make it work at this point). I suggest at this point that you host the application using some http server. Off the top of my head, I'd suggest that you install node package manager (npm), install [http-server](https://www.npmjs.com/package/http-server), run the server at the root of the application, and then point the manifest SourceLocation element at http://127.0.0.1:8080/#/add-in/word.

**Comment by MIchaelMainer** [comment]
I'll take a look at this issue and your other issues a bit later.

**Comment by giorgio79** [comment]
Thx will look at the localhost option (I use xampp :) It may not be possible, as the Trusted Addin Catalog only seem to accept https locations. Hoping onedrive or sg else can be used for hosting the addon if http fails.

**Comment by giorgio79** [comment]
Not sure if you did sg, but the snippet explorer started working from the local network share, so all fine and dandy.

**Comment by MIchaelMainer** [comment]
Very good to hear!
