### ISSUE TITLE
Word: "Select a range" snippet not selecting the inserted text

### ISSUE THREAD

**Issue by giorgio79** [OfficeDev/office-js-snippet-explorer#14]
Hello,

I am running the "Select a range" demo snippet, but the inserted text is not selected. (I assume this selection would be the equivalent of selecting a part of the text with the mouse).

**Comment by MIchaelMainer** [comment]
@giorgio79 - This should select the text as if you did it with a mouse. Just to make sure we're on the same page, is this the sample: https://github.com/OfficeDev/office-js-snippet-explorer/blob/master/word-snippets/rangeselect.js? This sample is working for me with Word version 16.0.6225.1000, targeting https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js for the library. Can you tell me what is the version of Word you're using?

**Comment by giorgio79** [comment]
Thx @MIchaelMainer, yes that is the sample, and I have 16.0.4 sg, but Word says I have the latest when I try to update. May need to wait a bit, until that version comes to Europe.
Anyway, I managed to get your sample one lines work here, and that is just perfect for me :)
https://github.com/OfficeDev/office-js-snippet-explorer/issues/15
