### ISSUE TITLE
Word: Search Text and Zoom to / Scroll to result?

### ISSUE THREAD

**Issue by giorgio79** [OfficeDev/office-js-snippet-explorer#15]
Hello,

I would like to search the text in a Word document, and zoom/scroll to the result. If the doc has mutliple pages, zooming/scrolling does not seem possible at the moment. Say I have a 10 page doc, and I have search results on pages 2 and 4. How can I scroll to the appropriate page?

**Comment by MIchaelMainer** [comment]
@giorgio79 You'll need to do a range.select() on each search result item. The Word UI with scroll to the selection. If you have more than one search result, you'll need to handle navigating between the selected ranges.

For example, in this [search sample](https://github.com/OfficeDev/office-js-snippet-explorer/blob/master/word-snippets/searchWholeWord.js), if you add the following in the loop:

<code>
if (i === searchResults.items.length - 1)
{
     searchResults.items[i].select();
}
</code>

the UI will select and scroll to the last search result.

**Comment by giorgio79** [comment]
Wow, yes that works wonders. Much appreciated @MIchaelMainer
