### ISSUE TITLE
Error "The Find What text contains a Pattern Match  expression which is not valid"

### ISSUE THREAD

**Issue by giorgio79** [OfficeDev/office-js-snippet-explorer#16]
Given the text "Why!!"

And searching for 
> var searchResults = context.document.body.search('!!', {matchWildCards: true});

I am getting an error popup saying ""The Find What text contains a Pattern Match  expression which is not valid" 
Is an exclamation mark a pattern? If yes, it is undocumented at https://github.com/OfficeDev/office-js-docs/blob/master/word/word-add-ins-javascript-reference/searchoptions.md

**Comment by MIchaelMainer** [comment]
It is part of a pattern. That option is the 7th one down in the Wildcard Guidance section. It is used to exclude characters in a search. For example, if you used 'the[!m,n]' as the search pattern, the results can be 'the', 'there', but not 'them' or 'then'. 

Turn of wild card search to find that string.

**Comment by giorgio79** [comment]
Ok thx! Will do. I was under the impression the square brackets are required for the exclamation as a wildcard, but I guess not then. :)

**Comment by bappidatta** [comment]
I am getting this error when try to use {*} expression to search {SomeValue}.
