### ISSUE TITLE
Content Controls Collection in Content Control

### ISSUE THREAD

**Issue by bogacg** [OfficeDev/office-js-snippet-explorer#17]
In Word snippets (and documentation) I see content control class now has content controls collection.
Does that mean we can now use Repeating Section Content Control? I'd like to create a table after importing data from a web service. 
Using HTML coercion type isn't very productive for table creation. An example for that with new API methods would be great, or at least some comments in snippets.
Thanks

**Comment by MIchaelMainer** [comment]
@bogacg Thank you for the question and feedback. The API currently supports just a Rich Text Content Control. Table creation is a top priority for this API. While we wait for this to be implemented, your option is to create a table using OOXML.
