### ISSUE TITLE
"The argument is invalid or missing" exception with multiple rows add operation.

### ISSUE THREAD

**Issue by bogacg** [OfficeDev/office-js-snippet-explorer#19]
I try to add multiple rows at once
`ctx.workbook.tables.getItem('myTable').rows.add(0,my2DArray);`

I get this error on add function (TableRowCollection.add):
>The argument is invalid or missing or has an incorrect format.

Is it not possible to add multiple rows at once? Or is there a restriction per cell value which I'm missing.
Thanks

**Comment by bogacg** [comment]
From what I understand, rows.add only works for 1 row at a time. 2D array shall not contain multiple rows data.

**Comment by Zlatkovsky** [comment]
Correct, rows.add only works for one row at a time for now, but we do have a suggestion bug for supporting 2D arrays as well.  I will use this as another example where folks have wanted this.  @sumurthy
