### ISSUE TITLE
Add table rows for two tables on one sheet

### ISSUE THREAD

**Issue by bogacg** [OfficeDev/office-js-snippet-explorer#20]
Adding rows to tables works fine if one table exists per sheet.
I've tried adding rows to two tables located on same sheet and that operation fails.

(One table on top of other with few empty rows in between, update fails even there would be no superposition if update took place)

Is this expected?

EDIT: having two tables on same sheet is not the problem indeed. When one table is on top of other, it gives error, even though there are enough rows inbetween.

**Comment by sumurthy** [comment]
I this has been fixed. I am no longer able to re-create this issue.
