### ISSUE TITLE
Add-in works for one user account but not the other

### ISSUE THREAD

**Issue by harrchen** [OfficeDev/office-js-snippet-explorer#23]
I have a 2016 VM with Office 2016 installed.  I have 2 user accounts.  I followed the exact step to setup the login (trusted catalog) for both accounts.  However, add-in works for one user.  For the other user, the add-in loads but didn't function - you can see dropdown list for group but cannot select it.

**Comment by keyur32** [comment]
Hi @harrchen,  it looks like we have an email thread for this issue internally, but for folks, this add-in is no longer supported. Instead we recommend users to use the is no longer supported. To get the latest snippets for Office-JS, we recommend developers to try the [Script Lab](https://store.office.com/en-001/app.aspx?assetid=WA104380862&ui=en-US&rs=en-001&ad=US&appredirect=false) add-in as we will plan to keep this up to date.
